### ISSUE TITLE
allowDangerousCharacters is still encoding '&' when its set to true

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [syntax-tree/hast-util-to-html#11]
Hi am trying to create an HTML by setting option ``allowDangerousCharacters: true`` & ``allowDangerousHTML: true`` but still the characters are being encoded.

Here is the example for what I am trying 
`<span v-if="(activeTab >= 3) && (activeTab < 5)">This is the fourth tab</span>
` but the characters are being encoded to this
`<span v-if="(activeTab >= 3) &#x26;&#x26; (activeTab < 5)">This is the fourth tab</span>`

**Comment by JayaKrishnaNamburu** [comment]
Sandbox [example](https://codesandbox.io/s/nrw41rx58m)

**Comment by wooorm** [comment]
Right, but this works as intended. `.allowDangerousCharacters` allows some more dangerous characters. `.allowDangerousHTML` does something entirely different, whether you need it depends on your stack.

However, what’s the problem? Seems you’re using a Vue template instead of actual HTML. Does Vue complain about `&#x26;`? This library cannot generate invalid HTML, and I don’t think it should. You could use something like [webparser from prettyhtml](https://github.com/Prettyhtml/prettyhtml) though, which is made using this library / ecosystem but is for Vue and the like.

**Comment by JayaKrishnaNamburu** [comment]
Thanks for the suggestions, will look into them 👍
