### ISSUE TITLE
Do not use `Omit` type

### ISSUE THREAD

**Issue by wooorm** [syntax-tree/hast-util-to-html#19]
```
  types/index.d.ts:25:7
  ✖  25:7  Don't use Omit as a type. Prefer the Except type in the type-fest package instead as it's stricter.  @typescript-eslint/ban-types
```

dtslint 3 complains about these lines, what should we do?

https://github.com/syntax-tree/hast-util-to-html/blob/0fef5aa542e1d8a9361f3a0ea8e38adf07fa870f/types/index.d.ts#L24-L26

/cc @Rokt33r as you wrote the types

**Comment by Rokt33r** [comment]
In my opinion, the rule can be ignored. `Omit` doesn't check the omitted props exist in `StringifyEntitiesOptions`. So if we replace it with `Except` from type-fest, it would be a little bit helpful for us to detect trivial typos when we rename the omitted props in `StringifyEntitiesOptions`. And I don't think we would like to rename them that often. So i think we can just disable banning usage of `Omit` rather than introducing more dev deps.

@ChristianMurphy How do you think?

**Comment by ChristianMurphy** [comment]
I'd agree, I think adding another `devDependency` would like cause more frustration than the benefit `Except` brings. We can probably safely disable this rule.

**Comment by Rokt33r** [comment]
Awesome! I'll make a pull request to fix this issue.

**Comment by Rokt33r** [comment]
@wooorm How can I reproduce the error message? Apparently we aren't using typescript-eslint rules for this repository.

**Comment by wooorm** [comment]
I think updating dtslint to 3 gave me that error.
Xo does have typescript-eslint internally I believe

**Comment by wooorm** [comment]
Ah, I turned them off while updating: https://github.com/syntax-tree/hast-util-to-html/commit/1b34d255e94990bb2e2717c726cf5a7ced03da57

**Comment by Rokt33r** [comment]
I see. I'll discard the comment and try to fix it again.

**Comment by Rokt33r** [comment]
@wooorm Hmm I think we can just close this issue now. I've checked the code again and I like the fix currently applied. We use `Omit` only once in this package so I don't think it is worth to configure the rule in package.json.

**Comment by wooorm** [comment]
OK! Thanks for looking into it & working on it!
