### ISSUE TITLE
How do I allow camel cased properties?

### ISSUE THREAD

**Issue by johnjeng** [syntax-tree/hast-util-to-html#5]
My use case is that some 3rd party library uses camel case properties
```
<div forLibrary='thing'> ... <div>
```
but this gets converted automatically to
```
<div for-library='thing'> ... <div>
```

**Comment by johnjeng** [comment]
Actually, it seems like an svg issue...

I want
```
<svg view-box="0 0 400000 200" preserve-aspect-ratio="xMinYMin slice">
```
to be
```
<svg viewBox="0 0 400000 200" preserveAspectRatio="xMinYMin slice">
```

**Comment by lottamus** [comment]
We are seeing the same issue with `viewBox` property getting converted to `view-box` on svg's. 

http://tutorials.jenkov.com/svg/svg-viewport-view-box.html#viewbox

**Comment by StarpTech** [comment]
You can fork it and remove the kebab-case conversion here https://github.com/syntax-tree/hast-util-to-html/blob/06c268d1e4d20e398adaf5a275227775739cee18/lib/element.js#L132

**Comment by wooorm** [comment]
Hey all!

Sorry for the delay!

I thought about it a bit and I’d like to work on this now. For starters, this issue is now first tracked in https://github.com/wooorm/property-information/issues/6. When that is done, we can work on updating it throughout the ecosystem.

I’ll close this now, if you have any further comments please post them there!
